language: go

go:
  - "1.13"

# Specify which branches to build using a safelist
# 分支白名单限制：只有 master 分支的提交才会触发构建
branches:
  only:
    - master

before_install:
    - export TZ='Asia/Shanghai'

install: 
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_0.73.0_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version

before_script:
    - rm -rf public
    
script:
    - hugo --theme=tranquilpeak --buildDrafts
    - echo 'Hugo build done!'

after_script:
  # 部署
  - cd ./public
  - git init
  - git config user.name "nlbsn"
  - git config user.email "1042038872@qq.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master
  # Github Pages
  - git push --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master --tags

env:
 global:
   # Github Pages
   - GH_REF: https://github.com/NLBSN/NLBSN.github.io.git

deploy:
    provider: pages     # 重要，指定这是一份github pages的部署配置
    skip_cleanup: true  # 重要，不能省略
    local_dir: public   # 静态站点文件所在目录
    target_branch: master   # 要将静态站点文件发布到哪个分支
    github_token: $GITHUB_TOKEN # 重要，$GITHUB_TOKEN是变量，需要在GitHub上申请、再到配置到Travis
    on:
        branch: master  # 博客源码的分支
    repo: NLBSN/NLBSN.github.io
#    fqdn: "" # 如果是自定义域名，此处要填
    keep-history: true # 是否保持target-branch分支的提交记录
    email: 1042038872@qq.com
    name: nlbsn